services:
  - type: web
    name: laundry-order-api
    runtime: docker
    rootDir: LaundryOrderSystem/Backend/LaundryOrderAPI
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://votre-app.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: laundry-db
          property: connectionString

databases:
  - name: laundry-db
    plan: free
