services:
  - type: web
    name: laundry-order-api
    runtime: docker
    rootDir: LaundryOrderSystem/Backend/LaundryOrderAPI
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://votre-app.vercel.app
      - key: DATABASE_URL
        value: postgresql://laundry_sl4l_user:H95YHEGd9zEj59Svshyq4hXvtkgtzoVt@dpg-d13ebep5pdvs73dm4o40-a/laundry_sl4l

databases:
  - name: laundry-db
    plan: free
